In [22]:
import cv2
import numpy as np

In [23]:
img = cv2.imread('data/train/cat.0.jpg')

In [24]:
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

In [25]:
img.shape

(374, 500, 3)

In [6]:
img = cv2.resize(img, (50, 50)) 

In [7]:
img.shape

(50, 50, 3)

In [8]:
img

array([[[ 91, 168, 207],
        [ 98, 176, 217],
        [105, 183, 226],
        ...,
        [145, 219, 249],
        [133, 212, 248],
        [124, 204, 244]],

       [[ 91, 168, 207],
        [ 98, 176, 217],
        [105, 183, 226],
        ...,
        [147, 221, 251],
        [141, 216, 247],
        [129, 208, 246]],

       [[ 93, 166, 210],
        [100, 174, 218],
        [103, 178, 222],
        ...,
        [145, 219, 249],
        [135, 218, 246],
        [136, 214, 247]],

       ...,

       [[ 61, 132, 166],
        [ 63, 134, 170],
        [ 66, 137, 174],
        ...,
        [  1,   6,   5],
        [  1,   6,   5],
        [  1,   4,   4]],

       [[ 56, 127, 161],
        [ 60, 131, 167],
        [ 63, 134, 171],
        ...,
        [  0,   4,   3],
        [  0,   4,   3],
        [  0,   3,   3]],

       [[ 56, 124, 155],
        [ 59, 129, 161],
        [ 61, 133, 167],
        ...,
        [  1,   3,   3],
        [  1,   3,   3],
        [  1,   3,   3]]

In [11]:
vgg_mean = np.array([123.68, 116.779, 103.939], dtype=np.float32)

In [12]:
img = img - vgg_mean

In [13]:
img

array([[[ -32.68     ,   51.221    ,  103.061    ],
        [ -25.68     ,   59.221    ,  113.061    ],
        [ -18.68     ,   66.221    ,  122.061    ],
        ...,
        [  21.32     ,  102.221    ,  145.061    ],
        [   9.32     ,   95.221    ,  144.061    ],
        [   0.3199997,   87.221    ,  140.061    ]],

       [[ -32.68     ,   51.221    ,  103.061    ],
        [ -25.68     ,   59.221    ,  113.061    ],
        [ -18.68     ,   66.221    ,  122.061    ],
        ...,
        [  23.32     ,  104.221    ,  147.061    ],
        [  17.32     ,   99.221    ,  143.061    ],
        [   5.3199997,   91.221    ,  142.061    ]],

       [[ -30.68     ,   49.221    ,  106.061    ],
        [ -23.68     ,   57.221    ,  114.061    ],
        [ -20.68     ,   61.221    ,  118.061    ],
        ...,
        [  21.32     ,  102.221    ,  145.061    ],
        [  11.32     ,  101.221    ,  142.061    ],
        [  12.32     ,   97.221    ,  143.061    ]],

       ...,

      

In [15]:
img[:, ::-1]

array([[[   0.3199997,   87.221    ,  140.061    ],
        [   9.32     ,   95.221    ,  144.061    ],
        [  21.32     ,  102.221    ,  145.061    ],
        ...,
        [ -18.68     ,   66.221    ,  122.061    ],
        [ -25.68     ,   59.221    ,  113.061    ],
        [ -32.68     ,   51.221    ,  103.061    ]],

       [[   5.3199997,   91.221    ,  142.061    ],
        [  17.32     ,   99.221    ,  143.061    ],
        [  23.32     ,  104.221    ,  147.061    ],
        ...,
        [ -18.68     ,   66.221    ,  122.061    ],
        [ -25.68     ,   59.221    ,  113.061    ],
        [ -32.68     ,   51.221    ,  103.061    ]],

       [[  12.32     ,   97.221    ,  143.061    ],
        [  11.32     ,  101.221    ,  142.061    ],
        [  21.32     ,  102.221    ,  145.061    ],
        ...,
        [ -20.68     ,   61.221    ,  118.061    ],
        [ -23.68     ,   57.221    ,  114.061    ],
        [ -30.68     ,   49.221    ,  106.061    ]],

       ...,

      

In [18]:
x = np.array([-32.68, 51.221, 103.061], dtype=np.float32)